= Test Sphere
Armando Sanchez Medina https://github.com/Armandorev[Armandorev]
[.lead]
Inspired by a very interesting conference about Wiremock, I found Sham, and based on Sham ( a library to generate random test data ) I have created this project to generate test data with data I am used to work with.

Now I'm using a builder strategy for creating the object. The way for building a person
== Person Class
Includes

* Person class
** Personal Information
*** Name
*** Surname
*** Middle Name
*** Age

=== Use samples:

==== Person()
Generate a Person with Default configuration (Receiving random name , surname and middle git ciname with a probability of 5%).
[source,java]
----
Person personGenerated = new Person.PersonBuilder().build();
----

==== Person with middle name
Generate a person with a probability of 100% of having a middle name
[source,java]
----
Person personGenerated = new Person.PersonBuilder()
        .withPersonalInformation(new PersonalInformation.PersonalInformationBuilder()
                        .withMiddleName().build()
        ).build();
----

Generate a person with a probability of having a middle name from 0(none) to 1(100%)
[source,java]
----
//50% of having a middle name -> 0.5
Person personGenerated = new Person.PersonBuilder()
        .withPersonalInformation(new PersonalInformation.PersonalInformationBuilder()
                        .withMiddleName(0.5D).build()
        ).build();
----
==== Person setting attributes
Generate a person with name Armando, Middle name Sanchez and Surname Medina.
[source,java]
----
Person personGenerated = new Person.PersonBuilder()
        .withPersonalInformation(new PersonalInformation.PersonalInformationBuilder()
                        .withName("Armando").withMiddleName("Sanchez").withSurname("Medina").build()
        ).build();
----
